# credits: https://github.com/deependujha
# from deepflow.publisher.telegram import TelegramPublisher
from deepflow.renderer import video_renderer


def main() -> None:
    # publisher = TelegramPublisher()
    # publisher.publish(
    #     "deepflow_sample.mp4", {"description": "A video generated by DeepFlow!"}
    # )
    # print("Hello from deepflow!")
    video_renderer(
        output_filename="deepflow_sample.mp4",
        frames_dir="silence/frames",
        collisions_log="silence/collisions_log.json",
        audio_dict={"crash": "silence/game-over.mp3"},
    )


def pipeline() -> None: ...
