# credits: https://github.com/deependujha
from deepflow.publisher.telegram import TelegramPublisher


def main() -> None:
    publisher = TelegramPublisher()
    publisher.publish(
        "deepflow_sample.mp4", {"description": "A video generated by DeepFlow!"}
    )
    print("Hello from deepflow!")
