# credits: https://github.com/deependujha

# from deepflow_engine.publisher.telegram import TelegramPublisher
# from deepflow_engine.renderer import video_renderer


def main() -> None:
    # publisher = TelegramPublisher()
    # publisher.publish(
    #     "DeepFlow-Engine_sample.mp4", {"description": "A video generated by DeepFlow-Engine!"}
    # )
    # video_renderer(
    #     output_filename="DeepFlow-Engine_sample.mp4",
    #     frames_dir="silence/frames",
    #     collisions_log="silence/collisions_log.json",
    #     audio_dict={"crash": "silence/game-over.mp3"},
    # )
    print("Hello from DeepFlow-Engine!")


def pipeline() -> None: ...
